### ISSUE TITLE
Re:Notify/Notifications bug + Module Message issue

### ISSUE THREAD

**Issue by Street-y** [amogus-client/bugs#2]
**Notify/Notifications** in the client is always stuck on toggled, even if you turned the module off. It still shows up in chat.

**Module messages don't save (e.g - changing "client" to "[client]"**

**Comment by zopac** [comment]
that is because it checks if the setting is enabled not the module open up the notify settings and turn off totem pop or module message which ever one u want

**Comment by ghost** [comment]
problem?
