### ISSUE TITLE
CSGO Watermark alignment error

### ISSUE THREAD

**Issue by Street-y** [amogus-client/bugs#5]
Fix placement/alignment please

the gaps and lengths hurt my eyes
![www](https://user-images.githubusercontent.com/58587212/124233107-d78d5900-db55-11eb-89f5-99b47abd18a7.PNG)

**Comment by zopac** [comment]
thats bc u have customfont on for some reason it stops rendering the unicode in the box it would look a lot nicer if u didnt have it on
