### ISSUE TITLE
Greeter/Welcomer Text is weird

### ISSUE THREAD

**Issue by Street-y** [amogus-client/bugs#6]
Why does it look like this?
![www](https://user-images.githubusercontent.com/58587212/124233282-06a3ca80-db56-11eb-931f-b22bb9a532b0.PNG)

**Comment by zopac** [comment]
u mean with the font janky as shit or something else

**Comment by Street-y** [comment]
> u mean with the font janky as shit or something else

yeah its fried up compared to other hud elements
